version: "3.6"

services:

  mysql_db:
    container_name: mysql-db
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql 
    ports:
      - "3306:3306"
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  rest_api:
    container_name: rest-api
    restart: always
    image: rest_api:spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      DATABASE_HOST: mysql_db
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: 3306    
    depends_on:
      - mysql_db

  nginx:
    container_name: nginx
    image: nginx:1.16
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - rest_api

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8082"
    volumes:
      - ./swagger/swagger-ui.yaml:/swagger-ui.yaml
    environment:
      SWAGGER_JSON: /swagger-ui.yaml
      PORT: 8082


volumes:
  mysql_data: